version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: server_db_1
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DB}"
      # So you don't have to use root, but you can if you like
      # You can use whatever password you like
      MYSQL_PASSWORD: "${MYSQL_PASS}"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      -  "${MYSQL_PORT}:${MYSQL_PORT}"
    expose:
      # Opens port 3306 on the container
      - "${MYSQL_PORT}"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

networks:
  default:
    name: foodemp-bridge
    external: true
# Names our volume
volumes:
  my-db: