"""empty message

Revision ID: 8a3b71812267
Revises: 
Create Date: 2022-07-06 17:30:11.407279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3b71812267'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=128), nullable=True),
    sa.Column('organization_name', sa.String(length=32), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('non_profit_license_num', sa.String(length=32), nullable=True),
    sa.Column('license_documentation_url', sa.String(length=64), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(length=32), nullable=True),
    sa.Column('food_license_number', sa.String(length=32), nullable=True),
    sa.Column('license_documentation_url', sa.String(length=64), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(length=128), nullable=True),
    sa.Column('user_email', sa.String(length=32), nullable=True),
    sa.Column('user_password', sa.String(length=32), nullable=True),
    sa.Column('device_token', sa.String(length=256), nullable=True),
    sa.Column('is_logged_in', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=128), nullable=True),
    sa.Column('city_name', sa.String(length=20), nullable=False),
    sa.Column('street_name', sa.String(length=20), nullable=False),
    sa.Column('street_number', sa.String(length=20), nullable=False),
    sa.Column('postal_code', sa.String(length=6), nullable=False),
    sa.Column('building_name', sa.String(length=20), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_name', 'street_name', 'street_number'),
    sa.UniqueConstraint('street_number', 'postal_code')
    )
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('best_before', sa.String(length=12), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foods')
    op.drop_table('addresses')
    op.drop_table('login')
    op.drop_table('donors')
    op.drop_table('customers')
    op.drop_table('users')
    # ### end Alembic commands ###
