"""empty message

Revision ID: a5433fde5b4f
Revises: 8a3b71812267
Create Date: 2022-07-12 21:22:02.579111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5433fde5b4f'
down_revision = '8a3b71812267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_filter',
    sa.Column('customers_id', sa.Integer(), nullable=True),
    sa.Column('filters_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customers_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['filters_id'], ['filters.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_filter')
    op.drop_table('filters')
    # ### end Alembic commands ###
