"""empty message

Revision ID: f8e369789c23
Revises: a5433fde5b4f
Create Date: 2022-07-12 21:25:41.349461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e369789c23'
down_revision = 'a5433fde5b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donationassoc',
    sa.Column('donation_id', sa.Integer(), nullable=True),
    sa.Column('filter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donationassoc')
    # ### end Alembic commands ###
